In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

folder_path = "/content/drive/MyDrive/healthcare"

In [ ]:
os.listdir(folder_path)

['employee.csv',
 'billing.csv',
 'department.csv',
 'admission.csv',
 'disease.csv',
 'bed.csv',
 'drug.csv',
 'insurance_provider.csv',
 'patient_diagnostic.csv',
 'billing_detail.csv',
 'diagnostic_test.csv',
 'staff_assignment.csv',
 'patient_insurance.csv',
 'patient.csv',
 'drug_inventory.csv',
 'drug_manufacturer.csv',
 'prescription.csv',
 'ward.csv',
 'doctor.csv']

In [ ]:
dataframes = {}

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        table_name = file.replace(".csv", "")
        dataframes[table_name] = pd.read_csv(os.path.join(folder_path, file))

print(dataframes.keys())

dict_keys(['employee', 'billing', 'department', 'admission', 'disease', 'bed', 'drug', 'insurance_provider', 'patient_diagnostic', 'billing_detail', 'diagnostic_test', 'staff_assignment', 'patient_insurance', 'patient', 'drug_inventory', 'drug_manufacturer', 'prescription', 'ward', 'doctor'])

In [ ]:
for name, df in dataframes.items():
    print("=" * 50)
    print(name.upper())
    print("=" * 50)
    print("Shape:", df.shape)
    print("\nMissing Values:")
    print(df.isnull().sum())
    print("\nDuplicates:", df.duplicated().sum())
    print("\nData Types:")
    print(df.dtypes)
    print("\n")

==================================================
EMPLOYEE
==================================================
Shape: (500, 7)

Missing Values:
employee_id        0
employee_name      0
gender             0
role               0
employment_type    0
date_of_joining    0
department_id      0
dtype: int64

Duplicates: 0

Data Types:
employee_id         int64
employee_name      object
gender             object
role               object
employment_type    object
date_of_joining    object
department_id       int64
dtype: object


==================================================
BILLING
==================================================
Shape: (45000, 8)

Missing Values:
bill_id                     0
bill_date                   0
total_amount                0
insurance_covered_amount    0
patient_payable_amount      0
payment_status              0
payment_mode                0
admission_id                0
dtype: int64

Duplicates: 0

Data Types:
bill_id                       int64
bill_date                    object
total_amount                  int64
insurance_covered_amount    float64
patient_payable_amount      float64
payment_status               object
payment_mode                 object
admission_id                  int64
dtype: object


==================================================
DEPARTMENT
==================================================
Shape: (11, 5)

Missing Values:
department_id      0
department_name    0
department_type    0
floor_number       0
status             0
dtype: int64

Duplicates: 0

Data Types:
department_id       int64
department_name    object
department_type    object
floor_number        int64
status             object
dtype: object


==================================================
ADMISSION
==================================================
Shape: (45000, 10)

Missing Values:
admission_id        0
admission_date      0
discharge_date      0
admission_type      0
admission_status    0
patient_id          0
department_id       0
ward_id             0
bed_id              0
disease_id          0
dtype: int64

Duplicates: 0

Data Types:
admission_id         int64
admission_date      object
discharge_date      object
admission_type      object
admission_status    object
patient_id           int64
department_id        int64
ward_id              int64
bed_id               int64
disease_id           int64
dtype: object


==================================================
DISEASE
==================================================
Shape: (20, 3)

Missing Values:
disease_id          0
disease_name        0
disease_category    0
dtype: int64

Duplicates: 0

Data Types:
disease_id           int64
disease_name        object
disease_category    object
dtype: object


==================================================
BED
==================================================
Shape: (415, 4)

Missing Values:
bed_id        0
bed_number    0
bed_status    0
ward_id       0
dtype: int64

Duplicates: 0

Data Types:
bed_id         int64
bed_number    object
bed_status    object
ward_id        int64
dtype: object


==================================================
DRUG
==================================================
Shape: (250, 6)

Missing Values:
drug_id            0
drug_name          0
brand_name         0
drug_category      0
unit_cost          0
manufacturer_id    0
dtype: int64

Duplicates: 0

Data Types:
drug_id             int64
drug_name          object
brand_name         object
drug_category      object
unit_cost           int64
manufacturer_id     int64
dtype: object


==================================================
INSURANCE_PROVIDER
==================================================
Shape: (50, 5)

Missing Values:
insurance_provider_id    0
provider_name            0
provider_type            0
contact_details          0
coverage_limit           0
dtype: int64

Duplicates: 0

Data Types:
insurance_provider_id     int64
provider_name            object
provider_type            object
contact_details           int64
coverage_limit            int64
dtype: object


==================================================
PATIENT_DIAGNOSTIC
==================================================
Shape: (63269, 6)

Missing Values:
patient_diagnostic_id    0
test_date                0
result_status            0
admission_id             0
test_id                  0
doctor_id                0
dtype: int64

Duplicates: 0

Data Types:
patient_diagnostic_id     int64
test_date                object
result_status            object
admission_id              int64
test_id                   int64
doctor_id                 int64
dtype: object


==================================================
BILLING_DETAIL
==================================================
Shape: (112402, 5)

Missing Values:
billing_detail_id        0
charge_type              0
reference_id         67402
amount                   0
bill_id                  0
dtype: int64

Duplicates: 0

Data Types:
billing_detail_id      int64
charge_type           object
reference_id         float64
amount                 int64
bill_id                int64
dtype: object


==================================================
DIAGNOSTIC_TEST
==================================================
Shape: (9, 5)

Missing Values:
test_id          0
test_name        0
test_category    0
standard_cost    0
department_id    0
dtype: int64

Duplicates: 0

Data Types:
test_id           int64
test_name        object
test_category    object
standard_cost     int64
department_id     int64
dtype: object


==================================================
STAFF_ASSIGNMENT
==================================================
Shape: (207, 4)

Missing Values:
assignment_id    0
employee_id      0
ward_id          0
shift            0
dtype: int64

Duplicates: 0

Data Types:
assignment_id     int64
employee_id       int64
ward_id           int64
shift            object
dtype: object


==================================================
PATIENT_INSURANCE
==================================================
Shape: (21617, 7)

Missing Values:
patient_insurance_id     0
policy_number            0
coverage_percentage      0
policy_start_date        0
policy_end_date          0
patient_id               0
insurance_provider_id    0
dtype: int64

Duplicates: 0

Data Types:
patient_insurance_id      int64
policy_number            object
coverage_percentage       int64
policy_start_date        object
policy_end_date          object
patient_id                int64
insurance_provider_id     int64
dtype: object


==================================================
PATIENT
==================================================
Shape: (30000, 6)

Missing Values:
patient_id        0
gender            0
date_of_birth     0
blood_group       0
city              0
contact_number    0
dtype: int64

Duplicates: 0

Data Types:
patient_id         int64
gender            object
date_of_birth     object
blood_group       object
city              object
contact_number    object
dtype: object


==================================================
DRUG_INVENTORY
==================================================
Shape: (250, 6)

Missing Values:
inventory_id         0
current_stock        0
reorder_level        0
inventory_status     0
last_restock_date    0
drug_id              0
dtype: int64

Duplicates: 0

Data Types:
inventory_id          int64
current_stock         int64
reorder_level         int64
inventory_status     object
last_restock_date    object
drug_id               int64
dtype: object


==================================================
DRUG_MANUFACTURER
==================================================
Shape: (300, 5)

Missing Values:
manufacturer_id       0
manufacturer_name     0
country               0
reliability_rating    0
contract_status       0
dtype: int64

Duplicates: 0

Data Types:
manufacturer_id         int64
manufacturer_name      object
country                object
reliability_rating    float64
contract_status        object
dtype: object


==================================================
PRESCRIPTION
==================================================
Shape: (73109, 6)

Missing Values:
prescription_id    0
dosage             0
frequency          0
duration_days      0
admission_id       0
drug_id            0
dtype: int64

Duplicates: 0

Data Types:
prescription_id     int64
dosage             object
frequency          object
duration_days       int64
admission_id        int64
drug_id             int64
dtype: object


==================================================
WARD
==================================================
Shape: (27, 5)

Missing Values:
ward_id          0
ward_name        0
ward_type        0
total_beds       0
department_id    0
dtype: int64

Duplicates: 0

Data Types:
ward_id           int64
ward_name        object
ward_type        object
total_beds        int64
department_id     int64
dtype: object


==================================================
DOCTOR
==================================================
Shape: (98, 5)

Missing Values:
doctor_id           0
employee_id         0
specialization      0
qualification       0
experience_years    0
dtype: int64

Duplicates: 0

Data Types:
doctor_id            int64
employee_id          int64
specialization      object
qualification       object
experience_years     int64
dtype: object

In [ ]:
df=pd.read_csv('/content/patient.csv')

In [ ]:
df1=pd.read_csv('/content/admission.csv')

In [ ]:
df2=pd.read_csv('/content/billing.csv')

In [ ]:
df4=pd.read_csv('/content/doctor.csv')

In [ ]:
df5=pd.read_csv('/content/department.csv')

In [ ]:
df6=pd.read_csv('/content/ward.csv')

In [ ]:
df7=pd.read_csv('/content/disease.csv')

## **Table:1**

In [ ]:
df.head()

,patient_id,gender,date_of_birth,blood_group,city,contact_number
0,1,Female,1987-08-24,O-,East Stephanieberg,+1-792-342-0981
1,2,Male,1960-05-18,A-,Manuelbury,793-725-0800
2,3,Male,1955-04-24,A-,Lake Susanchester,+1-330-617-3749x232
3,4,Male,2004-06-16,B-,South Leslieburgh,426-611-6235x07684
4,5,Male,1977-07-22,A-,Lopezchester,(215)330-2831x0821

In [ ]:
df.shape

(30000, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      30000 non-null  int64
 1   gender          30000 non-null  object
 2   date_of_birth   30000 non-null  object
 3   blood_group     30000 non-null  object
 4   city            30000 non-null  object
 5   contact_number  30000 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.4+ MB

In [ ]:
df['date_of_birth']=pd.to_datetime(df['date_of_birth'])

In [ ]:
df['city'].value_counts()

city
South Michael        32
Port Michael         26
New Michael          26
East Michael         26
South John           25
                     ..
Valerieport           1
New Virginiaburgh     1
Hamiltonport          1
Lake Carolchester     1
Latoyatown            1
Name: count, Length: 17836, dtype: int64

In [ ]:
df['city'].str.strip().str.title()

0        East Stephanieberg
1                Manuelbury
2         Lake Susanchester
3         South Leslieburgh
4              Lopezchester
                ...
29995         Port Lisaland
29996          West Gregory
29997          Mccoyborough
29998            East Laura
29999      New Sarahchester
Name: city, Length: 30000, dtype: object

In [ ]:
df['gender'].value_counts()

gender
Male      15918
Female    13478
Other       604
Name: count, dtype: int64

In [ ]:
df.drop(columns=['contact_number'],axis=1,inplace=True)

In [ ]:
df.describe()

         patient_id               date_of_birth
count  30000.000000                       30000
mean   15000.500000  1980-12-19 00:40:01.920000
min        1.000000         1935-02-09 00:00:00
25%     7500.750000         1958-02-27 12:00:00
50%    15000.500000         1981-03-16 12:00:00
75%    22500.250000         2003-10-06 06:00:00
max    30000.000000         2026-02-04 00:00:00
std     8660.398374                         NaN

In [ ]:
df.head()

   patient_id  gender date_of_birth blood_group                city
0           1  Female    1987-08-24          O-  East Stephanieberg
1           2    Male    1960-05-18          A-          Manuelbury
2           3    Male    1955-04-24          A-   Lake Susanchester
3           4    Male    2004-06-16          B-   South Leslieburgh
4           5    Male    1977-07-22          A-        Lopezchester

## **Table:2**

In [ ]:
df1.head()

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7

In [ ]:
df1.shape

(45000, 10)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   admission_id      45000 non-null  int64
 1   admission_date    45000 non-null  object
 2   discharge_date    45000 non-null  object
 3   admission_type    45000 non-null  object
 4   admission_status  45000 non-null  object
 5   patient_id        45000 non-null  int64
 6   department_id     45000 non-null  int64
 7   ward_id           45000 non-null  int64
 8   bed_id            45000 non-null  int64
 9   disease_id        45000 non-null  int64
dtypes: int64(6), object(4)
memory usage: 3.4+ MB

In [ ]:
df1['discharge_date']=pd.to_datetime(df1['discharge_date'])

In [ ]:
df1['admission_date']=pd.to_datetime(df1['admission_date'])

In [ ]:
df1['admission_type'].value_counts()

admission_type
Elective     26923
Emergency    18077
Name: count, dtype: int64

In [ ]:
df1['admission_status'].value_counts()

admission_status
Discharged    45000
Name: count, dtype: int64

In [ ]:
df1.describe()

,admission_id,admission_date,discharge_date,patient_id,department_id,ward_id,bed_id,disease_id
count,45000.000000,45000,45000,45000.000000,45000.000000,45000.00000,45000.00000,45000.000000
mean,22500.500000,2023-01-02 01:31:19.680000,2023-01-07 05:14:31.680000,14912.959911,3.159044,13.52620,194.59480,10.459844
min,1.000000,2020-01-01 00:00:00,2020-01-02 00:00:00,1.000000,1.000000,1.00000,3.00000,1.000000
25%,11250.750000,2021-07-02 00:00:00,2021-07-07 00:00:00,7390.750000,2.000000,7.00000,98.00000,5.000000
50%,22500.500000,2022-12-30 00:00:00,2023-01-04 00:00:00,14878.500000,3.000000,13.00000,195.00000,10.000000
75%,33750.250000,2024-07-09 00:00:00,2024-07-14 00:00:00,22411.000000,4.000000,20.00000,289.00000,15.000000
max,45000.000000,2025-12-31 00:00:00,2026-01-12 00:00:00,30000.000000,6.000000,27.00000,414.00000,20.000000
std,12990.525394,NaN,NaN,8659.657220,1.564617,7.34845,113.66573,5.771013

## **Table:3**

In [ ]:
df2.head()

,bill_id,bill_date,total_amount,insurance_covered_amount,patient_payable_amount,payment_status,payment_mode,admission_id
0,1,2025-05-26,68483,61634.7,6848.3,Paid,Insurance,1
1,2,2023-11-19,70917,35458.5,35458.5,Paid,Insurance,2
2,3,2023-02-20,28137,25323.3,2813.7,Pending,Insurance,3
3,4,2021-09-01,80665,64532.0,16133.0,Pending,Insurance,4
4,5,2021-07-13,54920,27460.0,27460.0,Pending,Insurance,5

In [ ]:
df2.shape

(45000, 8)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   bill_id                   45000 non-null  int64
 1   bill_date                 45000 non-null  object
 2   total_amount              45000 non-null  int64
 3   insurance_covered_amount  45000 non-null  float64
 4   patient_payable_amount    45000 non-null  float64
 5   payment_status            45000 non-null  object
 6   payment_mode              45000 non-null  object
 7   admission_id              45000 non-null  int64
dtypes: float64(2), int64(3), object(3)
memory usage: 2.7+ MB

In [ ]:
df2['bill_date']=pd.to_datetime(df2['bill_date'])

In [ ]:
df2['payment_status'].value_counts()

payment_status
Pending    22670
Paid       22330
Name: count, dtype: int64

In [ ]:
df2['payment_mode'].value_counts()

payment_mode
Insurance    35979
UPI           3049
Card          3017
Cash          2955
Name: count, dtype: int64

## **Table:5**

In [ ]:
df4.head()

   doctor_id  employee_id specialization qualification  experience_years
0          1            3    Orthopedics            DM                31
1          2            9     Pediatrics            MS                 7
2          3           13      Neurology            MS                21
3          4           25        Surgery            MS                25
4          5           26      Neurology          MBBS                 5

In [ ]:
df4.shape

(98, 5)

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         98 non-null     int64
 1   employee_id       98 non-null     int64
 2   specialization    98 non-null     object
 3   qualification     98 non-null     object
 4   experience_years  98 non-null     int64
dtypes: int64(3), object(2)
memory usage: 4.0+ KB

## **Table:6**

In [ ]:
df5.head()

   department_id    department_name department_type  floor_number  status
0              1          Emergency        Clinical             0  Active
1              2  Internal Medicine        Clinical             2  Active
2              3            Surgery        Clinical             3  Active
3              4         Pediatrics        Clinical             2  Active
4              5        Orthopedics        Clinical             4  Active

In [ ]:
df5.shape

(11, 5)

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    11 non-null     int64
 1   department_name  11 non-null     object
 2   department_type  11 non-null     object
 3   floor_number     11 non-null     int64
 4   status           11 non-null     object
dtypes: int64(2), object(3)
memory usage: 572.0+ bytes

## **Table:7**

In [ ]:
df6.head()

   ward_id         ward_name ward_type  total_beds  department_id
0        1  Emergency Ward 1   General          10              1
1        2  Emergency Ward 2   Private          15              1
2        3  Emergency Ward 3   General          10              1
3        4  Emergency Ward 4   General          20              1
4        5  Emergency Ward 5   General          20              1

In [ ]:
df6.shape

(27, 5)

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ward_id        27 non-null     int64
 1   ward_name      27 non-null     object
 2   ward_type      27 non-null     object
 3   total_beds     27 non-null     int64
 4   department_id  27 non-null     int64
dtypes: int64(3), object(2)
memory usage: 1.2+ KB

## **Table:8**

In [ ]:
df7.head()

   disease_id                 disease_name disease_category
0           1  Acute Myocardial Infarction          Cardiac
1           2                       Stroke     Neurological
2           3        Road Traffic Accident           Trauma
3           4                       Sepsis       Infectious
4           5   Acute Respiratory Distress      Respiratory

In [ ]:
df7.shape

(20, 3)

In [ ]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   disease_id        20 non-null     int64
 1   disease_name      20 non-null     object
 2   disease_category  20 non-null     object
dtypes: int64(1), object(2)
memory usage: 612.0+ bytes

In [ ]:
df8=pd.read_csv('/content/patient_diagnostic.csv')

In [ ]:
df8.head()

,patient_diagnostic_id,test_date,result_status,admission_id,test_id,doctor_id
0,1,2020-02-25,Normal,1,8,47
1,2,2020-02-25,Normal,1,2,43
2,3,2020-02-27,Abnormal,1,6,3
3,4,2022-03-04,Normal,2,1,3
4,5,2021-02-07,Abnormal,3,9,39

In [ ]:
df8.shape

(63269, 6)

In [ ]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63269 entries, 0 to 63268
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   patient_diagnostic_id  63269 non-null  int64
 1   test_date              63269 non-null  object
 2   result_status          63269 non-null  object
 3   admission_id           63269 non-null  int64
 4   test_id                63269 non-null  int64
 5   doctor_id              63269 non-null  int64
dtypes: int64(4), object(2)
memory usage: 2.9+ MB

In [ ]:
df8['test_date']=pd.to_datetime(df8['test_date'])

In [ ]:
df9=pd.read_csv('/content/bed.csv')

In [ ]:
df9

     bed_id bed_number bed_status  ward_id
0         1        1-1   Occupied        1
1         2        1-2   Occupied        1
2         3        1-3  Available        1
3         4        1-4   Occupied        1
4         5        1-5   Occupied        1
..      ...        ...        ...      ...
410     411      27-16   Occupied       27
411     412      27-17   Occupied       27
412     413      27-18  Available       27
413     414      27-19  Available       27
414     415      27-20   Occupied       27

[415 rows x 4 columns]

In [ ]:
df10=pd.read_csv('/content/drug.csv')
df10

,drug_id,drug_name,brand_name,drug_category,unit_cost,manufacturer_id
0,1,Earum,Arora-Pandya,Antibiotic,252,44
1,2,Minus,"Bhakta, Dass and Chakraborty",Antipyretic,243,240
2,3,Dolore,Kala Inc,Analgesic,13,215
3,4,Neque,"Bhargava, Andra and Nath",Antacid,356,7
4,5,Tempore,Lalla-Char,Antihypertensive,359,113
...,...,...,...,...,...,...
245,246,A,"Chada, Ahuja and Kala",Analgesic,337,149
246,247,Quisquam,"Warrior, Bhat and Maharaj",Antipyretic,19,223
247,248,Nostrum,Shetty LLC,Antihypertensive,483,140
248,249,Inventore,Tailor-Muni,Analgesic,391,145
249,250,Minus,Lala-Krishna,Antihypertensive,234,287

In [ ]:
df11=pd.read_csv('/content/prescription.csv')
df11

,prescription_id,dosage,frequency,duration_days,admission_id,drug_id
0,1,1 tablet,Twice a day,12,1,227
1,2,2 tablet,Twice a day,7,1,70
2,3,2 tablet,Thrice a day,3,1,234
3,4,2 tablet,Once a day,13,1,205
4,5,2 tablet,Twice a day,12,3,145
...,...,...,...,...,...,...
73104,73105,2 tablet,Twice a day,7,44999,118
73105,73106,1 tablet,Once a day,14,44999,48
73106,73107,2 tablet,Twice a day,10,45000,134
73107,73108,1 tablet,Thrice a day,11,45000,219
73108,73109,2 tablet,Thrice a day,12,45000,44

In [ ]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73109 entries, 0 to 73108
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   prescription_id  73109 non-null  int64
 1   dosage           73109 non-null  object
 2   frequency        73109 non-null  object
 3   duration_days    73109 non-null  int64
 4   admission_id     73109 non-null  int64
 5   drug_id          73109 non-null  int64
dtypes: int64(4), object(2)
memory usage: 3.3+ MB

In [ ]:
temp=df1.merge(df[['patient_id','date_of_birth']],on='patient_id',how='left')

In [ ]:
df1['Age_at_admission'] = ((temp['admission_date'] - temp['date_of_birth']).dt.days/365.25).astype('int64')

In [ ]:
df1['Age_group']=pd.cut(df1['Age_at_admission'],bins=[0,18,35,50,65,120],labels=['0-18','19-35','36-50','51-65','65+']
)

In [ ]:
df1.head()

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,Age_at_admission,Age_group
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,65,51-65
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,33,19-35
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,76,65+
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,4,0-18
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,7,0-18

In [ ]:
df1=df1.rename(columns={'Age_group':'Age_band'})

In [ ]:
df1['Age_Group'] = pd.cut(
    df1['Age_at_admission'],
    bins=[0, 17, 35, 55, 120],
    labels=['Child', 'Young Adult', 'Adult', 'Senior Citizen']
)

In [ ]:
df1.head()

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,Age_at_admission,Age_band,Age_Group
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,65,51-65,Senior Citizen
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,33,19-35,Young Adult
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,76,65+,Senior Citizen
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,4,0-18,Child
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,7,0-18,Child

In [ ]:
df1['length_of_stay']=(df1['discharge_date']-df1['admission_date']).dt.days

In [ ]:
df1['stay_category']=pd.cut(df1['length_of_stay'],bins=[0,3,7,14,float('inf')],labels=['Short','Medium','Long','Extended long'])

In [ ]:
df2['Insurance_Coverage_Pct'] = (
    df2['insurance_covered_amount'] / df2['total_amount'] * 100
).round(2)

In [ ]:
df2['Insurance_Coverage_Pct'].value_counts()

Insurance_Coverage_Pct
90.0    9135
70.0    9068
50.0    9026
0.0     9021
80.0    8750
Name: count, dtype: int64

In [ ]:
df2['Patient_Payment_Pct'] = (
    df2['patient_payable_amount'] / df2['total_amount'] * 100
).round(2)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   bill_id                   45000 non-null  int64
 1   bill_date                 45000 non-null  datetime64[ns]
 2   total_amount              45000 non-null  int64
 3   insurance_covered_amount  45000 non-null  float64
 4   patient_payable_amount    45000 non-null  float64
 5   payment_status            45000 non-null  object
 6   payment_mode              45000 non-null  object
 7   admission_id              45000 non-null  int64
 8   Insurance_Coverage_Pct    45000 non-null  float64
 9   Patient_Payment_Pct       45000 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(2)
memory usage: 3.4+ MB

In [ ]:
def coverage_category(x):
  if x==100:
    return 'Fully Insured'
  elif x==0:
    return 'Self Pay'
  else:
    return 'Partially Insured'

In [ ]:
df2['coverage_category']=(df2['Insurance_Coverage_Pct'].apply(coverage_category))

In [ ]:
df2.head()

,bill_id,bill_date,total_amount,insurance_covered_amount,patient_payable_amount,payment_status,payment_mode,admission_id,Insurance_Coverage_Pct,Patient_Payment_Pct,coverage_category
0,1,2025-05-26,68483,61634.7,6848.3,Paid,Insurance,1,90.0,10.0,Partially Insured
1,2,2023-11-19,70917,35458.5,35458.5,Paid,Insurance,2,50.0,50.0,Partially Insured
2,3,2023-02-20,28137,25323.3,2813.7,Pending,Insurance,3,90.0,10.0,Partially Insured
3,4,2021-09-01,80665,64532.0,16133.0,Pending,Insurance,4,80.0,20.0,Partially Insured
4,5,2021-07-13,54920,27460.0,27460.0,Pending,Insurance,5,50.0,50.0,Partially Insured

In [ ]:
df2['Bill_Category'] = pd.cut(
    df2['total_amount'],
    bins=[0,5000,15000,30000,float('inf')],
    labels=['Low','Medium','High','Very High']
)

In [ ]:
from google.colab import files

In [ ]:
df.to_csv('Cleaned_Patient.csv',index=False)

In [ ]:
files.download('Cleaned_Patient.csv')

In [ ]:
df1.to_csv('Cleaned_admission.csv',index=False)

In [ ]:
files.download('Cleaned_admission.csv')

In [ ]:
df2.to_csv('Cleaned_billing.csv',index=False)

In [ ]:
files.download('Cleaned_billing.csv')

In [ ]:
df4.to_csv('Cleaned_Doctor.csv',index=False)

In [ ]:
files.download('Cleaned_Doctor.csv')

In [ ]:
df5.to_csv('Cleaned_Department.csv',index=False)

In [ ]:
files.download('Cleaned_Department.csv')

In [ ]:
df6.to_csv('Cleaned_Ward.csv',index=False)

In [ ]:
files.download('Cleaned_Ward.csv')

In [ ]:
df7.to_csv('Cleaned_Disease.csv',index=False)

In [ ]:
files.download('Cleaned_Disease.csv')

In [ ]:
df8.to_csv('Cleaned_Patient_Diagnostic.csv',index=False)

In [ ]:
files.download('Cleaned_Patient_Diagnostic.csv')

In [ ]:
df9.to_csv('Cleaned_Bed.csv',index=False)

In [ ]:
files.download('Cleaned_Bed.csv')

In [ ]:
df10.to_csv('Cleaned_Drug.csv',index=False)

In [ ]:
files.download('Cleaned_Drug.csv')

In [ ]:
df11.to_csv('Cleaned_Prescription.csv',index=False)

In [ ]:
files.download('Cleaned_Prescription.csv')